Start Exception Handling and Builder Pattern
michael-mezgo/fh-movies pull request #51
Opened 2023-06-10 16:07 UTC by EP1210

Ich habe versucht das Builder Pattern zu implementieren. Allgemein bin ich mir nicht sicher ob das so oder anders gedacht war. Gebt mir gerne eine Rückmeldung beziehungsweise reden wir morgen darüber.

2023-06-10 23:12 UTC, elimei1 requested changes
Gefällt mir sehr gut wie du das gelöst hast. Auch super, dass der Start nun in einem try ist. Habe aber ein paar Änderungswünsche: Den Package Namen ändern, statt exercise4_Erik in bspw. builder oder so. Die Methode result würde ich in build umbenennen(heißt ja auch Builder Pattern). Den auskommentierten, alten Code in MovieAPI löschen und auch das ungenutzte import entfernen. Der Code schaut gut aus, die Änderungen sind nur optisch. Danke

2023-06-11 09:25 UTC, michael-mezgo requested changes
**Aus meiner Sicht wären folge Punkte wichtig auszubessern:**

- Die `result()`-Methode in `MovieURLBuilder` in der fertigen URL wirklich nur die Parameter ausgeben, welche befüllt sind. (Wenn Genre nicht gesetzt ist, sollte die URL nicht &genre="" mitgeben.) Das bitte unbedingt ändern
- Der Package-Name `at.ac.fhcampuswien.fhmdb.exercise4_Erik` sollte umbenannt werden.
- Der auskommentierte Code kann gelöscht werden. Falls wir ihn mal wieder brauchen, haben wir diesen in den alten Commits.

---

**Sachen, die mir für das Organisatorische wichtig sind:**
- Bitte das Issue auf der rechten Seite unter "Development" referzenzieren, damit wir einen Überblick haben, was noch erledigt gehört.

2023-06-11 09:25 UTC, michael-mezgo commented on src/main/java/at/ac/fhcampuswien/fhmdb/FhmdbApplication.java
> +import at.ac.fhcampuswien.fhmdb.exercise4_Erik.MovieURLBuilder;
Rename Package (e.g. ... . BuilderPattern), or move to fhmdb-Package

2023-06-11 09:25 UTC, michael-mezgo commented on src/main/java/at/ac/fhcampuswien/fhmdb/FhmdbApplication.java
> +        Alert homeAlert = new Alert(Alert.AlertType.ERROR, "The application stopped working!");
I would add that the reason is that (GUI / display) files were not found. Otherwise the user would check if their network is working, ...

2023-06-11 09:25 UTC, michael-mezgo commented on src/main/java/at/ac/fhcampuswien/fhmdb/exercise4_Erik/MovieURLBuilder.java
> +        return URL + "?query=" + query + "&genre=" + genre + "&releaseYear=" + releaseYear + "&ratingFrom=" + ratingFrom;
All those properties that were not set shouldn't be send empty.

2023-06-11 09:25 UTC, michael-mezgo commented on src/main/java/at/ac/fhcampuswien/fhmdb/models/MovieAPI.java
> +import at.ac.fhcampuswien.fhmdb.exercise4_Erik.MovieURLBuilder;
Package name!

2023-06-11 09:25 UTC, michael-mezgo commented on src/main/java/at/ac/fhcampuswien/fhmdb/models/MovieAPI.java
> +    /*
Delete legacy code. If we need this later, we can restore it using VCS (GitHub).

2023-06-11 15:05 UTC, michael-mezgo approved these changes

2023-06-11 15:07 UTC, elimei1 approved these changes

2023-06-11 15:08 UTC, merged